apiVersion: v1
kind: Service
metadata:
  name: web1-service
  namespace: app-cluster
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: web1