apiVersion: v1
kind: Service
metadata:
  name: web1-service
  namespace: app-cluster
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32112
  type: NodePort